Add PoC prototype with core functionality
ekotik/sh.wrap pull request #32
Opened 2022-12-17 08:36 UTC by burriedalive

## Add PoC prototype with core functionality

This PoC introduces a concept of module with scope for shell scripts. Current functionality is limited to module search and import.

PoC has no parser, instead it uses combination of \`source\` and \`declare\` to serialize module definitions. Serialized module is injected into a separate shell process spawned with \`env\`.

PoC saves \`module scope\` in special variable \`\_shwrap_scope\`. A module can change its own and other scopes without name collisions.

Usual shell scripts could be imported without changes but with some considerations. In this implementation it\'s preferred if a module contains only function and variable definitions as code execution may affect module functionality in an unexpected manner.

This PoC adds two user commands \`shwrap_import\` and \`shwrap_run\`.

\`shwrap_import\` is for module imports. \`shwrap_run\` is for command execution in a module scope.

### Examples of usage

``` bash
shwrap_import module.sh
shwrap_import module.sh function_name
shwrap_import module.sh function_name1 function_name2 ...

shwrap_run module.sh variable=value
shwrap_run module.sh function_name argument1 argument2 ...
shwrap_run module.sh '{ declare -p; declare -f}'
echo "Hello, sh.wrap!" | shwrap_run module.sh cat
```

When a name is imported from a module it becomes available for usage as a wrapper to \`shwrap\_run\` with the same name. No renaming of imported names is currently supported. Default import (the first example) imports only exported function names (with \`declare -fx\`).

### Module search

Module name could be relative or absolute path. If module name starts with \`./\` or \`../\` its considered a relative. If it starts with \`/\` it is absolute. If it\'s not a relative or absolute path, module is searched in the special locations in order. Firstly \`SHWRAP\_MODULE\_PATHS\` are checked. Module could extend its own search paths by adding relative or absolute paths to this variable. Also user can change it globally. Then load paths are checked. That are the paths of modules that are in the import chain of the module. Then \`SHWRAP\_MODULE\_PATH\` is checked which default is \`\~/.sh.wrap\`. As a fallback we keep current directory if something is broken in the previous search paths.

The order of search:

-   absolute paths
-   relative paths
-   SHWRAP_MODULE_PATHS
-   load paths
-   SHWRAP_MODULE_PATH
-   current directory

For example, these are valid module names

``` bash
shwrap_import /home/username/script.sh # (absolute path)
shwrap_import ./module.sh              # (relative path)
shwrap_import ../../module.sh          # (relative path)
shwrap_import dir/module.sh            # (searched relative to a special locations)
shwrap_import module.sh                # (searched relative to a special locations)
```

### PoC limitations

Limitations of this PoC implementation:

-   no arguments could be passed to modules (TBD)
-   no runnable scripts are supported (as arguments couldn't be passed)
-   user can\'t unset globally exported variables from execution environment with 'unset` command (TBD)
-   names with \`_shwrap_\` and \`_SHWRAP_\` prefixes are considered reserved and shouldn\'t be used
-   limited redirections support (as random file descriptors are used by core functions. TBD)
-   shwrap_import and shwrap_run user functions and core of shwrap don't support scope updates when asynchronously running or running in subshell (because of lack of synchronization)
-   bash is the only supported shell currently. Version 4.3+ or greater (tested in 5.2.2)

Although current PoC implementation supports cyclic module loading (to break \`source\` infinite loops) it\'s better to avoid such cases. Supposed to be changed in future when a syntax parser will be implemented and applied to the core functions. Current logic for cyclic module dependencies is to use partially imported modules at the point where cyclic import occurs. When modules are imported partial imports are fixed.

PoC uses cache when it imports module, so code from module is executed only once (same behavior as in Python).

Issues in this PoC implementation:

-   cache race condition between shell processes. one bash environment could write to cache while other read it
-   possible race on file descriptors (PoC has no support for asynchronous running).
-   performance issues. running command in a module scope in slower because of work that should be done. module import is slow too
-   no return codes checking and no reverting changes for unsuccessful import 
-   when fds are not enough it's broken. for example, it happens on deep imports

2022-12-17 08:50 UTC, ekotik requested changes

2022-12-17 08:50 UTC, ekotik commented on src/util.sh
> +	declare -p | grep -vE '_+shwrap_.*|BASHOPTS|BASH_ARGC|BASH_ARGV|BASH_LINENO|BASH_SOURCE|BASH_VERSINFO|EUID|FUNCNAME|GROUPS|PPID|SHELLOPTS|UID' | __shwrap_declare
Filter upper case definitions too.

2022-12-17 08:50 UTC, ekotik commented on src/run.sh
> +		# shellcheck disable=SC2046
Add shellcheck excuses everywhere

2022-12-17 08:50 UTC, ekotik commented on src/run.sh
> +	local fd_scope fd_scope_cap fd_out fd_out_cap
What range of fds do you suggess to reserve? Let's assume that we always have at least 1024 for now.

2022-12-17 08:50 UTC, ekotik commented on src/import.sh
> +	local module="$1"
May be. It deserves to be prefixed too. It's for our consistency and their uniformity.

2022-12-17 08:58 UTC, burriedalive commented on src/run.sh
> +	local fd_scope fd_scope_cap fd_out fd_out_cap
Well. It's complicated. We must find a number range that doesn't affect others' feelings.
Let see... let it be from 666 (because everyone loves Satan) to 777 (for those who like to get drunk).

2022-12-17 09:12 UTC, ekotik commented on src/run.sh
> +	local fd_scope fd_scope_cap fd_out fd_out_cap
666 and 777 are polite numbers. Let's steal 111 user file descriptors for the needs of ours.

2022-12-17 09:17 UTC, burriedalive commented on src/import.sh
> +	local module="$1"
I think we should be  more diverse and give those variables a chance to be different.

2022-12-17 09:20 UTC, ekotik commented on src/import.sh
> +	local module="$1"
Hmmm. OK. No prefixes for this little nice exceptional variable. BUT others vars should be prefixed with no exceptions.

2022-12-17 09:30 UTC, burriedalive commented on src/run.sh
> +		# shellcheck disable=SC2046
Sorry. Sometimes I forget to apologize.

2022-12-17 09:37 UTC, ekotik commented on src/search.sh
> +	# check user paths
misplaced comment

2022-12-17 23:53 UTC, burriedalive commented on src/import.sh
> +	local module="$1"
I've changed my mind. Local variables have no rights for uniqueness. They should follow our rules - sameness in naming with no exceptions.

2022-12-17 23:57 UTC, ekotik commented on src/import.sh
> +	local module="$1"
I don't mind. Erase them all.

2022-12-18 00:01 UTC, burriedalive commented on src/run.sh
> +	local fd_scope fd_scope_cap fd_out fd_out_cap
I used a non inclusive, but polite interval of [666;777). Users that are not with us could specify a range of fds thay think is good for them in SHWRAP_FD_RANGE variable.

2022-12-20 11:33 UTC, ekotik approved these changes

2022-12-20 11:51 UTC, merged